### ISSUE TITLE
Upgrading to React Native 0.64.0 breaks the build

### ISSUE THREAD

**Issue by Aleksefo** [audienceproject/userreport-react-native-sdk#4]
Hi,

After updating React Native I get the following error:
error: index.js: Transformer is not a constructor

This is due to the library requiring an old version of React Native:
└─┬ @audienceproject/react-native-userreport-sdk@3.0.2
  └─┬ react-native@0.63.4
    └─┬ @react-native-community/cli@4.14.0
      ├─┬ metro@0.59.0
      │ └── metro-config@0.59.0  deduped
      └── metro-config@0.59.0 

Can you please update the library to use the latest React Native?

**Comment by NikolayFrantsev** [comment]
I've pushed new version 3.0.3 with updated dependencies.
Thanks for your report, feel free to open new issue if you'll have any problems.
